export const ACCOUNT_FETCH = "ACCOUNT_FETCH";
export const ACCOUNT_FETCH_SUCCESS = "ACCOUNT_FETCH_SUCCESS";
export const ACCOUNT_FETCH_START = "ACCOUNT_FETCH_START";
export const ACCOUNT_FETCH_ERROR = "ACCOUNT_FETCH_ERROR";

export const ACCOUNT_GET_REDIRECT_URL = "ACCOUNT_GET_REDIRECT_URL";
export const ACCOUNT_GET_REDIRECT_URL_SUCCESS =
  "ACCOUNT_GET_REDIRECT_URL_SUCCESS";
export const ACCOUNT_GET_REDIRECT_URL_START = "ACCOUNT_GET_REDIRECT_URL_START";
export const ACCOUNT_GET_REDIRECT_URL_ERROR = "ACCOUNT_GET_REDIRECT_URL_ERROR";

export const ACCOUNT_SAVE = "ACCOUNT_SAVE";
export const ACCOUNT_SAVE_SUCCESS = "ACCOUNT_SAVE_SUCCESS";
export const ACCOUNT_SAVE_START = "ACCOUNT_SAVE_START";
export const ACCOUNT_SAVE_ERROR = "ACCOUNT_SAVE_ERROR";
