export const ANALYTIC_ACCOUNT_FETCH = "ANALYTIC_ACCOUNT_FETCH";
export const ANALYTIC_ACCOUNT_FETCH_SUCCESS = "ANALYTIC_ACCOUNT_FETCH_SUCCESS";
export const ANALYTIC_ACCOUNT_FETCH_START = "ANALYTIC_ACCOUNT_FETCH_START";
export const ANALYTIC_ACCOUNT_FETCH_ERROR = "ANALYTIC_ACCOUNT_FETCH_ERROR";
