export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_START = "AUTH_REGISTER_START";
export const AUTH_REGISTER_ERROR = "AUTH_REGISTER_ERROR";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_EMAIL_RESEND = "AUTH_EMAIL_RESEND";
export const AUTH_EMAIL_VERIFY = "AUTH_EMAIL_VERIFY";
export const AUTH_EMAIL_RESEND_SUCCESS = "AUTH_EMAIL_RESEND_SUCCESS";
export const AUTH_EMAIL_VERIFY_SUCCESS = "AUTH_EMAIL_VERIFY_SUCCESS";
