#!/usr/bin/env bash

# Handles all build steps on the jenkins instance
# all jenkins should do is call this file.
# NOTE: this script expects to be called from the root of the project, NOT from the build_scripts folder

set -e

npm run clean
echo ':: Installing  Now'

npm install
echo ':: Building  Now'
npm run build

cp -r /home/neeraj/Projects/smart2.0/smartanalytics-web/build/.  /home/neeraj/Deployment-production/Smartanalytics/smartanalytics-web


